### ISSUE TITLE
[Feature] Chuck boundry and light level overlays.

### ISSUE THREAD

**Issue by ZombieKM** [ThePansmith/CABIN#10]
**Is your feature request related to a problem? Please describe.**
There is no overlay for chunk boundary or light levels. Or at least none that I can find.

**Describe the solution/mod you'd like**
There is a mod 'More Overlays Updated' that has these overlays available for forge 1.18.2. I tried adding it myself, but encountered a crash, so I don't know if it is compatible with this pack.

**Additional context**
N/A

[x] This is something I believe would fit the base pack, and would not be better implemented as an addition to the compatibility script.

**Comment by ThePansmith** [comment]
The haunted bell can be used to see where mobs can spawn, you can pick one up in the questbook (or just craft it)
