### ISSUE TITLE
[BUG] Trade Station is not accessible by item transporting blocks

### ISSUE THREAD

**Issue by Lewis-Zhou8** [ThePansmith/CABIN#103]
When using the Trade Station, Items cannot be extracted by hopper, chute funnel or brass pipes. Coins cannot be inputed with any of the item transport methods stated. Brass pipes do not seem to connect to trade stations as it would to a chest or drawer.

1. Go to any world
2. Obtain a trade station and power it
3. Set the trade station to any import card
4. Place coins inside the trade station
5. Place hopper / chute below trade station
6. Trade station should make a trade as normal, but no output will be extracted by the hopper
Expected behavior**
Hopper, Brass Pipe, Chutes and Funnels should be able to interact with the trading station, allowing for automatic trading similar to the behavior in the original create above and beyond mod-pack.

<img width="1440" alt="Screenshot 2024-08-20 at 8 19 52 PM" src="https://github.com/user-attachments/assets/a8f526bc-2527-45b0-b035-0d7cd729a86a">

Notice the difference in connection with the brass pipe to the chest and furnace and the connection to the trade station. The connection to the chest is when a brass pipe is connected to an inventory, while connection to the trade station is the same as when the pipe is connected to a normal block.
<img width="1440" alt="Screenshot 2024-08-20 at 8 19 23 PM" src="https://github.com/user-attachments/assets/6f3a86e1-806e-42fe-8254-d8f467928bb6">
Side view
<img width="1440" alt="Screenshot 2024-08-20 at 8 19 59 PM" src="https://github.com/user-attachments/assets/e917c146-a7ef-4a65-826d-f0cdd205ab41">
Coins in top hopper 

<img width="1440" alt="Screenshot 2024-08-20 at 8 20 06 PM" src="https://github.com/user-attachments/assets/8da3b975-faf3-4604-82bb-f162cfbe7df9">
Trade station is not refilled with coins from the top hopper, and the gold is not extracted despite a hopper being beneath it.

<img width="1440" alt="Screenshot 2024-08-20 at 8 20 08 PM" src="https://github.com/user-attachments/assets/45410273-3cb6-479f-81fc-8ba3bb7ac701">
Empty outputs chest

**Comment by cubebotfan** [comment]
The trade station is a thermal machine, so it needs to have it's inputs and outputs configured in its configuration. If a face isn't set to input then no input will be accepted from that side. If a face isn't set to output, then no oututs will be pulled from that side.
![image](https://github.com/user-attachments/assets/6251aeab-1279-4362-b108-01f517cf3cfe)

**Comment by Lewis-Zhou8** [comment]
Thank you, I've basically tunnel visioned into create when I started to play modded so I'm not as knowledgable about other mods.
