### ISSUE TITLE
Consider adding Thermal Series - Create Version resource pack [Feature]

### ISSUE THREAD

**Issue by Bluemethyst** [ThePansmith/CABIN#13]
**Is your feature request related to a problem? Please describe.**
Thermal machines look out of place next to all your create machinery

**Describe the solution/mod you'd like**
Maybe consider adding this [Thermal Series - Create Version resource pack](https://www.curseforge.com/minecraft/texture-packs/thermal-series-create-version) to the modpack as it would fit the aesthetic very very well

**Additional context**

[x] This is something I believe would fit the base pack, and would not be better implemented as an addition to the compatibility script.

**Comment by chipsams** [comment]
the asthetics imply that the thermal machines would fit in the brass tier, instead of being their own tier, and the different color scheme is important to the machines feeling like a new kind of tool.
