### ISSUE TITLE
Curseforge Displayed version incorrect

### ISSUE THREAD

**Issue by Epicificator** [ThePansmith/CABIN#45]
**Describe the bug**
The version displayed on the Curseforge app is incorrect.

**To Reproduce**
1. Go to Curseforge app.
2. Look at the CABIN modpack card.
3. Look at version on the top right corner of modpack card.
4. You will see incorrect displayed version.

**Expected behavior**
I expected the correct version to be displayed, my CABIN was on version 1.1.1 yet the card displayed 1.0.0.

**Screenshots**
![image](https://github.com/ThePansmith/CABIN/assets/143143550/763b14ab-acfb-4556-9914-d67f3ab16521)

**Comment by ThePansmith** [comment]
Please consider looking into either prismlauncher or ATlauncher, as they can do everything curselauncher can do, but far better (and without ads).

**Comment by Epicificator** [comment]
telling me to change my launcher isnt fixing the issue, just ignoring it

**Comment by ThePansmith** [comment]
![image](https://github.com/ThePansmith/CABIN/assets/70342772/568a637c-4435-4389-9de4-b6c625bec81b)

**Comment by Epicificator** [comment]
i found a fix by not being lazy about updating stuff
