### ISSUE TITLE
[BUG] Items moving in Brass Item Pipes disappear upon world exit

### ISSUE THREAD

**Issue by MidQualityMochi** [ThePansmith/CABIN#47]
**Describe the bug**
Upon exiting a singleplayer world, any items that were currently moving through a brass item pipe disappear. Whether or not they are despawned or completely destroyed is unknown.

**To Reproduce**
1. Create a set-up of two chests connected by a chain of brass item pipes. For ease of replication, it's better to have chain be at least 4 pipes long.
2. In one of the chests, place a stack of items.
3. In the pipe adjacent to the chest you placed the items in, place a Low Extraction Module.
4. Wait a moment to allow items to begin moving through pipe network.
5. Save and Quit to Title while items are moving in pipe network.
6. Enter world. Upon reentering, it should be evident that the items previously moving through the pipes have disappeared, but for definitive proof, allow all items to move through the pipe network. You should see that there are less items in the receiving chest than was placed in the input chest. 

**Expected behavior**
Items that were currently moving through the pipes should remain in the pipes upon reentering a world, similar to how items remain on Mechanical Belts when exiting and entering a world.

**Additional Context**
Though I can't speak for the relevance of this information; Create: Above & Beyond demonstrates the expected behavior.
Also, this behavior occurs regardless of whether or not the chunk was loaded at the time of exiting.

**Comment by ThePansmith** [comment]
This is an issue for the pretty pipes devs, create an issue at their repo.
