### ISSUE TITLE
[BUG] Netherite Diving Suit does not provide enhanced lava vision

### ISSUE THREAD

**Issue by MidQualityMochi** [ThePansmith/CABIN#48]
**Describe the bug**
Despite wearing a full set of Netherite Diving Gear (Netherite Diving Helmet, Netherite Backtank, Netherite Leggings, and Netherite Diving Boots), vision in lava is not enhanced.

**To Reproduce**
1. Go into a world and equip all equipment listed above.
2. Submerge self entirely in lava.
3. See error (Vision is entirely taken up by orange/lava, you can barely see a block in front of you).

**Expected behavior**
Should be allowed to see for several blocks in front of you while in lava, which is cut off by a fog-like effect.

**Screenshots**
Screenshot demonstrating proper equipment
![2023-12-28_03 34 47](https://github.com/ThePansmith/CABIN/assets/155066175/4a8b25ef-f32a-4f65-ad4c-480841393ba4)
Screenshot demonstrating lack of vision
![2023-12-28_03 34 51](https://github.com/ThePansmith/CABIN/assets/155066175/c92d02b8-eafa-400d-abb0-51a5bd1f7b0d)
Screenshot demonstrating expected behavior (taken in a different modpack with Create)
![2023-12-28_03 38 50](https://github.com/ThePansmith/CABIN/assets/155066175/9025cc71-6e7a-479d-bfd5-2371477eb64c)

**Additional context**
It has been noted by the Create devs that Optifine is known to cause this issue; however the CABIN doesn't seem to have Optifine. Though maybe something related to it may be causing the issue. That's just my personal theory, however. As another side note, the modpack with the expected behavior is in version 1.20.1. This might be a contributing factor to why this issue occurs in CABIN, but not in the other modpack.

**Comment by cubebotfan** [comment]
This issues has been known for a while. I'm not sure exactly what mod causes it but I know that this modpack's performance mod, Embeddium is not the mod that causes the issue. We'd have to test out different mods to see which one is causing it and determine if there's a reasonable way to fix this.

**Comment by MidQualityMochi** [comment]
I decided to look into which mod is causing the issue, and I've discovered that it's specifically and only the Enlightend mod that is causing this issue (specific jar name: enlightend-5.0.10-1.18.2.jar). This is probably the most bizarre mod that could've possibly had this effect. Hopefully this information is useful.

**Comment by cubebotfan** [comment]
I've found that downgrading enlightened to version 4.0.0.1 fixes the bug but causes all items from the mod to be wiped from existing worlds. Downgrading enlightened also removes the upper end.

**Comment by cubebotfan** [comment]
I don't think there's a way to fix this without removing enlightened. The best we could do is add a kubejs script that gives the player fire resistance(improves lava vision slightly) when they have the netherite diving suit equipped.

**Comment by ThePansmith** [comment]
Fixed in 96467c8
