### ISSUE TITLE
[BUG?] Ruby/Sapphire/Cinnabar ores are way too rare

### ISSUE THREAD

**Issue by ehren-strifling** [ThePansmith/CABIN#6]
In this pack all redstone ores are removed because cinnabar ore is used instead... But the cinnabar spawn rates are extremely low, rarer than diamonds even in the right y-levels. This makes redstone nearly impossible to obtain without trading coins for it.

I'm also pretty sure that ruby and sapphire don't even spawn at all.

**Comment by ThePansmith** [comment]
fixed in [6234ba7](https://github.com/ThePansmith/CABIN/commit/6234ba7b7aa8e58bbcad8e2e4a6e05693630ccea)
