### ISSUE TITLE
[BUG] "Andesite Age" Advancement is unobtainable

### ISSUE THREAD

**Issue by UpsideDownFoxxo** [ThePansmith/CABIN#68]
**Describe the bug**
The "Andesite Age" Advancement added by Create still requires you to click a stripped log with an andesite alloy to obtain it. Since that recipe has been removed, the advancement can now no longer be obtained.

**Expected behavior**
Crafting Andesite Casings in the Crafting table should unlock this advancement

**Screenshots**
![image](https://github.com/ThePansmith/CABIN/assets/33359685/a1665c12-7df3-4a05-9342-b0ffe00f689c)

**Comment by UpsideDownFoxxo** [comment]
I can work on this myself if that is prefered, I just wanted to open an issue first.

**Comment by ThePansmith** [comment]
I'm not really too concerned with advancements (or do i know how they work lol), so if you want to fix it yourself go ahead.
