### ISSUE TITLE
[BUG] Andesite/Diorite/Granite barely generate naturally

### ISSUE THREAD

**Issue by ehren-strifling** [ThePansmith/CABIN#7]
Andesite/Diorite/Granite don't spawn in the ground like they normally do, instead they only rarely spawn in special stone veins. This makes early game extremely tedious to start up since the only reasonable way to obtain andesite is by creating an andesite generator at bedrock level.

**Comment by ehren-strifling** [comment]
Update: some cave biomes do spawn andesite/diorite/granite but most places are completely barren of these stone types

**Comment by ThePansmith** [comment]
Terralith "feature", spent the last bit trying to renable it, but terralith wouldn't cooperate so i just removed it for now.
