### ISSUE TITLE
[BUG] Gold coins are castable in tinkers smelteries.

### ISSUE THREAD

**Issue by ZombieKM** [ThePansmith/CABIN#8]
**Describe the bug**
Gold coins can be cast in tinkers construct smelters and melters at 3 nuggets per a coin.

**To Reproduce**
Pour molten gold in coin cast to get a gold coin.

**Expected behavior**
Coins should not be cast-able. Breaks the balance of the shop in the quest book.

**Screenshots**
N/A

**Additional context**
Silver coins are also cast-able, but as far as I know, there is no way to get silver besides the coins.

**Comment by ThePansmith** [comment]
Already fixed
