### ISSUE TITLE
Newer version?

### ISSUE THREAD

**Issue by JIAFALSEDREAM** [ThePansmith/CABIN#89]
Will CABIN have plans for a newer version, such as 1.20.1?
(Although Tinkers' Construct currently does not have 1.20.1,but I don't think that's a problem?)

And if I want to submit a PR, is there anything I need to pay attention to?

**Comment by cubebotfan** [comment]
1. CABIN is likely going to stay in 1.18.2.

2. I plan on releasing a major update really soon, those changes are saved on the CABIN 1.3 branch right now. https://github.com/ThePansmith/CABIN/tree/CABIN_1.3.0

**Comment by cubebotfan** [comment]
The main branch is now updated with the 1.3.0 content so it should be safe to make pull requests now.
