### ISSUE TITLE
[BUG] Many of the tool tips in the 'shipments' tab of the quest book display the wrong price.

### ISSUE THREAD

**Issue by ZombieKM** [ThePansmith/CABIN#9]
**Describe the bug**
In the quest book 'shipments' tab, hovering over an item displays the item's name and cost, but the cost displayed in the tooltip often does not match the actual price once the quest is clicked on.

**To Reproduce**
Go to the 'shipments' tab in the quest book. Hover 'dirt' for example. The tool tip says '16x dirt 2 silver'. Click on the quest. The price is 10 silver. Repeat for each quest.

**Expected behavior**
An easy fix would be to simply remove the price from the tool tip.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by ThePansmith** [comment]
The price shown refers to how much you would need to spend to get those items, not the cost of the card itself
